# Generated by Django 2.2.1 on 2019-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Coin')),
                ('ieotime_date', models.DateField(verbose_name='Date')),
                ('ieoexchange', models.CharField(max_length=100, verbose_name='Exchange')),
                ('ieocost', models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Cost')),
                ('ieoprice', models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Price')),
                ('ieohighprice', models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Highest Price')),
                ('ieohighestuppercent', models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Highest Up Percent')),
                ('ieocurrentuppercent', models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Current Up Percent')),
            ],
        ),
    ]
