# Generated by Django 2.2.1 on 2019-07-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='ieocost',
            field=models.FloatField(verbose_name='成本'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieocurrentuppercent',
            field=models.FloatField(verbose_name='现价涨幅'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieoexchange',
            field=models.CharField(max_length=100, verbose_name='交易所'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieohighestuppercent',
            field=models.FloatField(verbose_name='最高涨幅'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieohighprice',
            field=models.FloatField(verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieoprice',
            field=models.FloatField(verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieotime_date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=100, verbose_name='币种'),
        ),
    ]
