# Generated by Django 2.2.1 on 2019-07-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20190717_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='ieocost',
            field=models.FloatField(verbose_name='IEO成本'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieocurrentuppercent',
            field=models.FloatField(default=0, verbose_name='现价涨幅'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieohighestuppercent',
            field=models.FloatField(default=0, verbose_name='最高涨幅'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieohighprice',
            field=models.FloatField(default=0.0, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieoprice',
            field=models.FloatField(default=0.0, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ieotime_date',
            field=models.DateField(verbose_name='上市日期'),
        ),
    ]
