# Generated by Django 2.2.1 on 2019-07-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_update'),
    ]

    operations = [
    ]
