# Generated by Django 2.2.1 on 2019-07-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_auto_20190722_1526'),
    ]

    operations = [
    ]
