# Generated by Django 2.2.1 on 2019-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0006_auto_20190722_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.AddField(
            model_name='coin',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
